name: StorageGUI
version: '1.0'
main: dev.felnull.storagegui.StorageGUI
api-version: '1.16'
depend:
  - BetterGUI
  - BetterStorage
  - Vault
commands:
  showstoragesoundlist:
    permission: storagegui.command.admin
    aliases: [sssl]
  soundreload:
    permission: storagegui.command.admin
  shownowstoragesound:
    permission: storagegui.command.admin
    aliases: [ snss ]
permissions:
  storagegui.command.admin:
    default: op